const PROJECTS = [
  {
    title: "i-teco",
    year: 2025,
    tags: ["Corporate", "Vue"],
    technologies: ["Vue.js", "JavaScript"],
    difficulty: 3,
    popularity: 7,
    image: "img/i-teco.webp",
    description: "Корпоративный сайт инжиниринговой компании",
    url: "https://www.i-teco.ru/services/construction-engineering",
    githubUrl: null,
  },
  {
    title: "yug-avto-tenet",
    year: 2025,
    tags: ["Landing", "Corporate", "Vue"],
    technologies: ["Vue.js", "JavaScript"],
    difficulty: 2,
    popularity: 8,
    image: "img/webp/1728b3d368f7ba22_1.webp",
    description: "Лендинг автодилера TENET",
    url: "https://yug-avto-tenet.ru/",
    githubUrl: null,
  },
  {
    title: "tank-yug-avto",
    year: 2025,
    tags: ["Landing", "Corporate", "Vue"],
    technologies: ["Vue.js", "JavaScript"],
    difficulty: 2,
    popularity: 7,
    image: "img/webp/tank-land.webp",
    description: "Промо-страница TANK",
    url: "https://tank-yug-avto.ru/",
    githubUrl: null,
  },
  {
    title: "Jaecoo",
    year: 2024,
    tags: ["Landing", "Corporate"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 2,
    popularity: 7,
    image: "img/webp/jaecoo.webp",
    description: "Лендинг автомобильного бренда Jaecoo",
    url: "https://yug-avto-jaecoo.ru/",
    githubUrl: null,
  },
  {
    title: "FursaMebel",
    year: 2024,
    tags: ["Corporate", "MODX"],
    technologies: ["MODX", "PHP", "JavaScript"],
    difficulty: 3,
    popularity: 8,
    image: "img/webp/fursa.webp",
    description: "Сайт мебельной компании",
    url: "https://fursamebel.ru/",
    githubUrl: null,
  },
  {
    title: "chess-landing",
    year: 2024,
    tags: ["Landing"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 1,
    popularity: 6,
    image: "img/webp/chess.webp",
    description: "Лендинг шахматного клуба",
    url: "https://andtheowind.github.io/chess-landing/",
    githubUrl: "https://andtheowind.github.io/chess-landing/",
  },
  {
    title: "Project",
    year: 2024,
    tags: ["Corporate", "MODX"],
    technologies: ["MODX", "PHP", "JavaScript"],
    difficulty: 2,
    popularity: 5,
    image: "img/webp/project.webp",
    description: "Корпоративный сайт проектной организации",
    url: "https://proekt-sev.ru/",
    githubUrl: null,
  },
  {
    title: "Offer",
    year: 2024,
    tags: ["Landing"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 1,
    popularity: 5,
    image: "img/webp/offer.webp",
    description: "Промо-страница специального предложения",
    url: "https://andtheowind.github.io/promoPage/",
    githubUrl: "https://andtheowind.github.io/promoPage/",
  },
  {
    title: "BSVR",
    year: 2024,
    tags: ["Corporate", "WordPress"],
    technologies: ["WordPress", "PHP", "JavaScript"],
    difficulty: 2,
    popularity: 6,
    image: "img/webp/bsvr-land.webp",
    description: "Лендинг строительной компании",
    url: "https://bsvr-group.ru/",
    githubUrl: null,
  },
  {
    title: "K-telecom",
    year: 2023,
    tags: ["Landing", "Corporate"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 2,
    popularity: 6,
    image: "img/webp/k-telecom-land.webp",
    description: "Лендинг телеком-оператора",
    url: "https://andtheowind.github.io/K-Telecom/",
    githubUrl: "https://andtheowind.github.io/K-Telecom/",
  },
  {
    title: "Bike",
    year: 2023,
    tags: ["Landing"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 1,
    popularity: 5,
    image: "img/webp/bike.webp",
    description: "Лендинг велосипедного магазина",
    url: "https://andtheowind.github.io/bike",
    githubUrl: "https://github.com/andTheowind/bike",
  },
  {
    title: "Orbigros",
    year: 2023,
    tags: ["Corporate", "WordPress"],
    technologies: ["WordPress", "PHP", "JavaScript"],
    difficulty: 3,
    popularity: 7,
    image: "img/webp/orbigros.webp",
    description: "Сайт оптовой торговли",
    url: "https://orbigrosperimetr.ru/",
    githubUrl: null,
  },
  {
    title: "iClub",
    year: 2023,
    tags: ["Corporate", "E-commerce", "WordPress"],
    technologies: ["WordPress", "PHP", "JavaScript"],
    difficulty: 2,
    popularity: 6,
    image: "img/webp/iclub.webp",
    description: "Сайт сервисного центра",
    url: "https://iclub-service.ru/",
    githubUrl: null,
  },
  {
    title: "WannaFly",
    year: 2023,
    tags: ["Landing", "WordPress"],
    technologies: ["WordPress", "PHP", "JavaScript"],
    difficulty: 1,
    popularity: 4,
    image: "img/webp/wannaFly.webp",
    description: "Лендинг авиационной тематики",
    url: "https://andtheowind.github.io/wannaFly",
    githubUrl: "https://github.com/andTheowind/wannaFly",
  },
  {
    title: "Tanatos",
    year: 2022,
    tags: ["Landing"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 2,
    popularity: 5,
    image: "img/webp/new7edd331611f3b5a0.webp",
    description: "Креативный лендинг",
    url: "https://andtheowind.github.io/Tanatos",
    githubUrl: "https://github.com/andTheowind/Tanatos",
  },
  {
    title: "Golden-Landing",
    year: 2022,
    tags: ["Landing"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 1,
    popularity: 5,
    image: "img/webp/new1728b3d368f7ba22.webp",
    description: "Золотой промо-лендинг",
    url: "https://andtheowind.github.io/Golden-landing",
    githubUrl: "https://github.com/andTheowind/Golden-landing",
  },
  {
    title: "Freshness",
    year: 2022,
    tags: ["Landing"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 2,
    popularity: 5,
    image: "img/webp/newdfghdfghdfghfgh.webp",
    description: "Лендинг продуктов питания",
    url: "https://andtheowind.github.io/Freshness",
    githubUrl: "https://github.com/andTheowind/Freshness",
  },
  {
    title: "Landing-Agenstv",
    year: 2022,
    tags: ["Landing"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 1,
    popularity: 4,
    image: "img/webp/new92696ca0018050bb.webp",
    description: "Лендинг рекламного агентства",
    url: "https://andtheowind.github.io/landing-Agenstv",
    githubUrl: "https://github.com/andTheowind/landing-Agenstv",
  },
  {
    title: "Project-Bauhandwerk",
    year: 2021,
    tags: ["Landing", "Corporate"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 2,
    popularity: 4,
    image: "img/webp/newdfghdfghdfjghjgfhj.webp",
    description: "Лендинг строительной компании",
    url: "https://andtheowind.github.io/Project-Bauhandwerk",
    githubUrl: "https://github.com/andTheowind/Project-Bauhandwerk",
  },
  {
    title: "Project-Merkury-Landing",
    year: 2021,
    tags: ["Landing"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 1,
    popularity: 4,
    image: "img/webp/new0c9eda4046f93ffa.webp",
    description: "Лендинг Merkury",
    url: "https://andtheowind.github.io/Project-Merkury-Landing",
    githubUrl: "https://github.com/andTheowind/Project-Merkury-Landing",
  },
  {
    title: "Project-Home",
    year: 2021,
    tags: ["Landing"],
    technologies: ["HTML", "CSS", "JavaScript"],
    difficulty: 1,
    popularity: 4,
    image: "img/webp/new86d6a1d14666f382.webp",
    description: "Лендинг домашней тематики",
    url: "https://andtheowind.github.io/Project-Home",
    githubUrl: "https://github.com/andTheowind/Project-Home",
  },
];
